stages:
  - build
  - test
  - deploy
  - final
    
.build-code:
  stage: build
  script:
    - echo "This step will build the code"
    - echo "Env Variable ${build_val}"

.test-code:
  stage: build
  script:
    - echo "This step will build the code"
    - echo "Env Variable ${test_val}"

.deploy-code:
  stage: build
  script:
    - echo "This step will build the code"
    - echo "Env Variable ${deploy_val}"

final_stage:
  stage: final
  script:
    - echo "This step will build the code"

